### ISSUE TITLE
The beta login message/lockout seems to get stuck.

### ISSUE THREAD

**Issue by nodra-vr** [Fayyr-Organization/fayyr-beta#11]
It pops up at random after clearing the cache and reloading a once or twice,  or browsing around for a second or two. It happens before and after login. All that I can see once it happens is the image below.

**Extra:** I have the sender wallet plugin installed but using NEAR web wallet for login.
**Using:** Brave Browser [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)]

The only message in the console is:
```
persisSignInStatus res:  {error: 'Please unlock sender first'}
```

And when sender is unlocked:
```
persisSignInStatus res:  {error: 'Please sign in first'}
```
**Visual Info**

![02-beta-ogin-issue](https://user-images.githubusercontent.com/93687805/166115202-acee25f8-a83f-4b91-9fff-4e8d33ddb105.png)

**Comment by BenKurrek** [comment]
It seems this account doesn't have access to the beta. If you'd like me to add you, I can do that for sure :)
