### ISSUE TITLE
Owned Art and Purchases remain empty after buying

### ISSUE THREAD

**Issue by nodra-vr** [Fayyr-Organization/fayyr-beta#12]
Bought two pieces, and 15 min (30 min) later nothing shows up on the website. The tokens are added to my account when checking the contract's state. 

**Console:**No logs at all.

**Using:** Brave Browser [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)]

**Transactions:**
https://explorer.testnet.near.org/transactions/G9viR6hmFhYisjDUdmvm4u6833XDrihpLXNZH3HvDWFe
https://explorer.testnet.near.org/transactions/8YfsTmqTaCqQErj1Sq3iRvhXsd4bWRQLX3JxmnQdx692

(sorry if I missed something stupid again, just playing dump smashing random buttons)

**Visual Info:**

![04-no-info-on-website](https://user-images.githubusercontent.com/93687805/166120984-0a6679d2-c703-4d38-b82b-b0bd0a896788.png)

**Comment by BenKurrek** [comment]
Hey! Thanks for bringing this up to us - our indexer was returning a 404 unfortunately and are working on a fix at the moment. Should be fixed shortly!

**Comment by nodra-vr** [comment]
Okay. A slow or failing indexer was in the back of my mind. It would be nice to have some indicator on the front-end when the backend starts producing errors.

**Comment by BenKurrek** [comment]
Yea - this really shouldn't be happening but if it does (and it shouldn't often), we'll alert people in discord or maybe have a banner on the site. Thanks for the heads up again!
