### ISSUE TITLE
QA: Layout - Miss Aligned Cards

### ISSUE THREAD

**Issue by nodra-vr** [Fayyr-Organization/fayyr-beta#13]
With the drop shadow and the line at the bottom of the cards, it feels as if they need to be aligned better. Both the bottom and the text elements of these cards should line up perfectly.

(If the layout is WIP: let us know and I will hold back on these issues.)

![06-miss-aligned cards](https://user-images.githubusercontent.com/93687805/166131824-cdcee184-821a-480f-a574-03144b564fa5.png)

Using: Brave Browser [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)]

**Comment by nodra-vr** [comment]
The offset does work in the image below, maybe aligning them at the bottom and creating the white space at the top would make it look better in cases where only two items are shown in the list. (after looking around a bit more, not so sure about this one)

![06 1-miss-aligned cards](https://user-images.githubusercontent.com/93687805/166232523-d568bfb0-45dc-4644-b4d3-6a3a36414b0d.png)

**Comment by WAEliasmith** [comment]
Yeah, it's tough to always make it look nice when the art can come in many shapes and sizes, so we decided to not crop most art, and just line up the start of the first two. These kinds of decisions are great for feedback though, so keep em coming!
