### ISSUE TITLE
QA: Layout - Content Scrollbars on Purchases list

### ISSUE THREAD

**Issue by nodra-vr** [Fayyr-Organization/fayyr-beta#14]
Scrollbars like these are just a bad experience for users. 
Solution: cut off long text and/or reduce the content on slim views.

The floating footer in the image below is messy.
Solution: Make sure the footer is pushed down to the bottom or make the background color of the page the same as the footer.

(If the layout is WIP: let us know and I will hold back on those issues.)

![05-bad-scroll-bar](https://user-images.githubusercontent.com/93687805/166132067-3a215b26-2bc6-41fd-a48e-5a8779681541.png)

Using: Brave Browser [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)]

**Comment by WAEliasmith** [comment]
Good points, I will add them to the backlog and we will have someone take a look
