### ISSUE TITLE
QA: Layout - Text behind and over buttons

### ISSUE THREAD

**Issue by nodra-vr** [Fayyr-Organization/fayyr-beta#15]
As the title says, text hides behind and shows over buttons. See image:

![07-manage-art-bad-text](https://user-images.githubusercontent.com/93687805/166199975-a229401b-8edb-4e40-b753-9b6785e2fcf4.png)

Using: Brave Browser [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)]

**Comment by WAEliasmith** [comment]
Nice catch, will add this to the backlog
