### ISSUE TITLE
Bug: Reversed Order on Owned Art Sorting

### ISSUE THREAD

**Issue by nodra-vr** [Fayyr-Organization/fayyr-beta#17]
The sorting order of art seems to be in reverse for 'Most Recent' and 'Oldest'. (Price sorting seems to be fine. But not 100% sure if the one item that is for sale is placed in the correct position.)

See Image:
![09-reverse-order-owned-art](https://user-images.githubusercontent.com/93687805/166221196-460a2b18-a40d-448a-a4ec-187aab5613dc.png)

Using: Brave Browser [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)]

**Comment by WAEliasmith** [comment]
I have done some testing, and for me it is nether in order of most recent purchase first or oldest purchase first for these sorts, so yeah something is going wrong here. It has been added to the backlog.
