### ISSUE TITLE
QA Suggestion: Add a link back to the parties involved

### ISSUE THREAD

**Issue by nodra-vr** [Fayyr-Organization/fayyr-beta#18]
I wanted to buy another one of an item I owned and put it up on the market but could not find the link? So the only way to go from owned art -> collection -> charity is to search? (Or after more clicking I found the link in the purchases tab)

Feel like the modal should link to the creator profile, collection, and charity as well?
![10-no-link-to-buy-more](https://user-images.githubusercontent.com/93687805/166408183-75b49c51-dd27-4c6a-9a8a-f699f3a71777.png)

**Comment by WAEliasmith** [comment]
Good idea, we want the site to be easy and intuitive to navigate, so these suggestions are really helpful!
