### ISSUE TITLE
QA Layout: The spacing/size of the title in "Manage Artwork"

### ISSUE THREAD

**Issue by nodra-vr** [Fayyr-Organization/fayyr-beta#19]
The title of the modal looks messy. Two extremes in the image down below.

* The Long title should have more separation from sales info
* The short one has no real reason to put it on two lines?

![11-mannage-artworc-title-bug](https://user-images.githubusercontent.com/93687805/166409657-4974fc22-9b1c-462e-b478-ea2c07bf0ea1.png)

Link: https://beta.fayyr.com/account/?tab=ownedArt
Using: Brave Browser [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)]

**Comment by WAEliasmith** [comment]
Yeah we have a few places where long titles make it awkward, we are thinking of truncating it so it will show ... after the character limit is reached. That two lines case is strange, will have to look into it!

**Comment by celiasmith** [comment]
Fixed for soft launch
