### ISSUE TITLE
NEAR wallet

### ISSUE THREAD

**Issue by neave1** [Fayyr-Organization/fayyr-beta#4]
In making a purchase I went to the "more information" button in the wallet and it didn't give me any. It was coding and irrelevant information.

**Comment by neave1** [comment]
Now that I own "Chateau Stairs", how do I access it on my devices?? Where is it stored?

**Comment by neave1** [comment]
Following my transaction, I was unable to have the links sent to my email address. The copy links button didn't work either. I requested a receipt but page showed a "server error" and did not respond. If I want to claim this art purchase on my income tax, I need a receipt.

**Comment by celiasmith** [comment]
> Following my transaction, I was unable to have the links sent to my email address. The copy links button didn't work either. I requested a receipt but page showed a "server error" and did not respond. If I want to claim this art purchase on my income tax, I need a receipt.

When you say you were 'unable' to have the links sent, did you enter an email address and hit the "send links" button and it failed in some way?  I can't reproduce a problem (it sends me an email properly).

When you say the copy links button doesn't work, did you try to paste anywhere after copying the links? I can't reproduce it not copying.

I also can't reproduce the server error on receipt request.  

Perhaps something has been fixed since you had these problems (a lot is changing during the beta). Please try each of these again.

**Comment by neave1** [comment]
Why do I need to add storage when I want to sell some art? If I am selling, I am opening up and increasing the storage which the art work was filling in my account.

**Comment by celiasmith** [comment]
> In making a purchase I went to the "more information" button in the wallet and it didn't give me any. It was coding and irrelevant information.

When there is a blue bar across the top of the screen, you are not on our website, your are on NEAR's site, so we can't do anything about the user experience there.

Unfortunately the 'more information' button seems to cancel the transaction if you hit the browser 'back' button. And the 'more information' they show you is for the crypto savvy.

**Comment by celiasmith** [comment]
> Why do I need to add storage when I want to sell some art? If I am selling, I am opening up and increasing the storage which the art work was filling.

The storage you are paying for is on the Market contract. The market needs to store information about the item you are selling, so you have to pay a (very small) fee for the space. After the piece is sold you get that fee back.

**Comment by celiasmith** [comment]
> Now that I own "Chateau Stairs", how do I access it on my devices?? Where is it stored?

It is in your account page in the 'owned art' tab. Here's a [link](https://fayyr.com/account/?tab=ownedArt).

**Comment by neave1** [comment]
> > In making a purchase I went to the "more information" button in the wallet and it didn't give me any. It was coding and irrelevant information.
> 
> When there is a blue bar across the top of the screen, you are not on our website, your are on NEAR's site, so we can't do anything about the user experience there.
> 
> Unfortunately the 'more information' button seems to cancel the transaction if you hit 'back'. And the 'more information' they show you is for the crypto savvy.

I didn't see a blue bar, but if I was on the wrong website, maybe a warning that I am leaving FAYYR would be appropriate. The transition was seamless.

**Comment by celiasmith** [comment]
Once the buttons (and bar across the top) turn blue, you're not on our site.  It is supposed to be seamless, to make it easy to perform transactions.  

It would be quite jarring to pop up a question every time that says 'are you sure you want to leave'. 

That being said, maybe there's a way we can pop up a brief message that says something like 'Going to your NEAR wallet to complete the transaction,' without waiting for permission to do so.  There's a bit of a delay anyway, so that might help people.

**Comment by neave1** [comment]
> > Following my transaction, I was unable to have the links sent to my email address. The copy links button didn't work either. I requested a receipt but page showed a "server error" and did not respond. If I want to claim this art purchase on my income tax, I need a receipt.
> 
> When you say you were 'unable' to have the links sent, did you enter an email address and hit the "send links" button and it failed in some way? I can't reproduce a problem (it sends me an email properly).
> 
> When you say the copy links button doesn't work, did you try to paste anywhere after copying the links? I can't reproduce it not copying.
> 
> I also can't reproduce the server error on receipt request.
> 
> Perhaps something has been fixed since you had these problems (a lot is changing during the beta). Please try each of these again.

I was able to copy the link and paste it to a Word file. There was no color change or button highlight to show that the copy had occurred. I purchased a new piece of art as I couldn't see how to get back to the links with the previous purchases and the send links button still did not respond and send me an email. I had a sever error message again.

**Comment by neave1** [comment]
Thanks, I have received your answers via email, I was working on the Github
issues page when I was respnding. However, I didn't receive my links via
email yet. Enough for tonight. LM

**Comment by celiasmith** [comment]
> I was able to copy the link and paste it to a Word file. There was no color change or button highlight to show that the copy had occurred. I purchased a new piece of art as I couldn't see how to get back to the links with the previous purchases and the send links button still did not respond and send me an email. I had a sever error message again.

You can get the art link by clicking on the art in the owned art tab, and copying the link in your browser URL bar.

Did you type in an email address before you hit the 'send links' button?  If there's no email address it can't send them and will remain greyed out.

I can't reproduce a server error.  If you want to send me a private email with the information you entered for that page, please do (don't respond to this if you see it as email, as that will be posted publicly)
