### ISSUE TITLE
Inconsistent search results 

### ISSUE THREAD

**Issue by MikeElias14** [Fayyr-Organization/fayyr-beta#5]
Navigating to search from art page (ie Clicking `#nature` from [This Art](https://fayyr.com/art/beta-nft.fayyr.testnet.token_14ea99cc-579d-4c06-a6ac-ce0d37f48b52_3)) returns: 
![image](https://user-images.githubusercontent.com/37086795/141237764-15806c18-4b8f-4365-9808-70008fe7a340.png)

Filtering by the `nature` tag from the gallery returns:
![image](https://user-images.githubusercontent.com/37086795/141237838-d7a7c2ba-31bc-4bc1-a53e-cd8ab619b74f.png)

Searching for `nature` from the gallery returns: 
![image](https://user-images.githubusercontent.com/37086795/141237886-c7a30cc4-4341-44e7-a826-d70e855afc5c.png)

**Comment by stevers16** [comment]
Thanks! Fixed in a branch....
