### ISSUE TITLE
Miscellaneous 

### ISSUE THREAD

**Issue by neave1** [Fayyr-Organization/fayyr-beta#6]
1. Respecting the Environment errors  -- participting - participating; comitted - committed; 
2. Exchanges not accepting transactions from the USA are Binance, Huobi & OKEx. Are you aware of this?
3. Spelling error in the official receipt -- Transfered - Transferred
4. Terms and Conditions -- "SECTION 1 - OVERVIEW
This website and any and any subdomains or other... " repeating "and any".
5."When you land on the NEAR wallet page, it will say 'Fayyr.com is request(ing) the transfer of..." step 5 of How to Use.
6."newly owned art and the blockhain ..." in Step 6 of How to Use, blockhain needs a "c".
7. under becoming an Artist step 5 - "like to tells about why you..." should be "like to tell us about why you...".
8. "Same as White glove no Art Assist, but..." capitalize Glove, under becoming a charity.

**Comment by celiasmith** [comment]
Thanks, made all the changes, except 5. as that's not on our website.
Yes, we are aware of the limitations of various exchanges, it definitely makes life challenging! (Binance is also banned in Ontario).

**Comment by neave1** [comment]
OK, should get a chance to do more tonight or tomorrow.
