### ISSUE TITLE
Distribution of Royalties

### ISSUE THREAD

**Issue by neave1** [Fayyr-Organization/fayyr-beta#7]
In the pie chart under metadata it shows that the charity gets 12% of royalties and I (as the owner) get 80%. Is that correct? As the owner I should not get any royalties. Is the title of the pie chart wrong? Are the %'s correct for the various portions? Royalties usually only go to the artist. What you are showing is the distribution of the price of the artwork, or the donation.

**Comment by celiasmith** [comment]
Yes this is correct. You purchased the art and the charity got most of what you spent. Then you own it. If you turn around and sell it again, you get the majority. With a normal art auction, if you resold something you bought, you'd get 100% of the proceeds, so our method is better for the charity.

**Comment by neave1** [comment]
Yes, I understand that. My point was that calling all of the distributions
royalties may be incorrect. Check the definition of royalties. Perhaps
"proceeds" would be a more accurate term.

**Comment by celiasmith** [comment]
I see. Yes we can think more about the terminology, if royalties is confusing.
