### ISSUE TITLE
Proofreading & Layout of Charity Descriptions

### ISSUE THREAD

**Issue by neave1** [Fayyr-Organization/fayyr-beta#8]
~NAMI Impact page -- Bold and a separate paragraph for each of "Our Vision", "Our Mission" and "Our Values" to clarify.
~TSO History page -- remove the irrelevant, bracketed numbers.
~TSO Impact page -- remove numbers, start with a capital letter.
~National Ballet History page -- hyphenate "in-house"
~National Ballet Impact page -- "Read our full commitment to EDI >" doesn't go anywhere, broken link
~JED Mission page -- needs a period at the end statement
~CAMH Impact page -- "communities Goals We" Lower case "g", period after goals, community's goals (showing possession)
~Powerplant Mission page -- period at the end
~NCC Impact page -- line 13 "conservation. Developing strategies" add "targets" after conservation. Also bold or italics for "Developing strategies",  "Taking action", "Measuring success:" Needs a period at the end.
~CODE Impact page -- commas after "Our vision, Our mission, Our core values"
~AGO  Mission page -- period at the end
~AGO History page -- "https://ago.ca/board-trustees-fact-sheet" broken link
~AGO Impact page -- this paragraph requires a re-write, it makes little sense from beginning to end, no closing period
~TRCA -- good description
~Contact Photography Festival -- good description
~Bridgepoint Health -- good description
~IRF History page -- needs a closing period
~IRF Impact page -- put colons after the capitalized headings
~Project AWARE Foundation History page -- remove irrelevant bracketed numbers
~Project AWARE Foundation Impact page -- "... platforms such as Facebook and My Ocean, " delete comma and put a period after My Ocean; "Project AWARE's online eco-network" (add in here) is dedicated to...; remove irrelevant bracketed numbers
~Global Association for People and the Environment -- good description
~Against Malaria Foundation Mission page -- closing period
~AMF Impact page -- delete braced words "{What we do} We help protect people from malaria. We fund anti-malaria nets, specifically long-lasting insecticidal nets (LLINs), and work with distribution partners to ensure they are used. We track and report on net use and malaria case data. {Donations} People fundraise for us, typically through sponsored activities. We also receive direct donations from individuals, groups and organisations. {more Distributions} We buy nets and work with distribution partners who organise and fund the distribution of the nets. {more Monitoring} We monitor net usage to ensure nets continue to be used. We monitor malaria case rate data so we know the impact of the nets. {more}"
~War Child Impact page -- "Humanitarian Standard War Child" period after Standard
~Last Door -- good description

**Comment by celiasmith** [comment]
Thanks for the thorough proofread!  This actually points to a deeper challenge, which is that we can't currently format these string (e.g. bold or even new line).  We've added a task to allow that formatting, and then we can return to these suggestions and implement them.

**Comment by neave1** [comment]
This proofreading wasn't everything. I just mentioned the main points that
I noticed. There was a lot more layout to be done to make the pages
attractive. I think that your target audience would notice these details
too. I hope you can work a fix. neave 😉

**Comment by celiasmith** [comment]
All of the descriptions have now been updated and formatted nicely.

**Comment by neave1** [comment]
I reviewed the updated pages and they look much improved, excellent layout. For me, as a donor, it would make a huge difference in my confidence in the website. I did find a few of the suggested changes that were missed, I have listed them below. 
I will continue to work on other aspects of the website. neave

~National Ballet Impact page -- Please remove the "Read our full commitment to EDI>" phrase. It is no longer relevant now that the link has been removed.
~JED Mission page -- needs a period at the end statement. Remains uncorrected.
~CAMH Impact page -- requires a period at the end of the first sentence.
~Powerplant Mission page -- period at the end
~NCC Impact page -- needs a period at the end.
~AGO Mission page -- needs a period at the end.
~Project AWARE Foundation History page -- remove irrelevant bracketed numbers, they look like numbered footnotes without the corresponding footnote
~Project AWARE Foundation Impact page -- Needs a period at the end of the second paragraph.
~Against Malaria Foundation Mission page -- Needs a closing period.

**Comment by neave1** [comment]
Issue #8 is not quite completed. Please see the comments on Github.

**Comment by celiasmith** [comment]
> Issue [#8](https://github.com/Fayyr-Organization/fayyr-beta/issues/8) is not quite completed. Please see the comments on Github.

Please check again. Those changes were made, but they took a while to propagate to the 'live' version of the website. Hopefully we got them all 🤞 . Thanks for the follow up.
